
openapi: 3.1.0
info:
  title: Admin Login API
  version: 1.0.0
  description: |
    로그인 전용 API 명세서. 쿠키 기반 세션을 사용하며, 세션 토큰의 원문은 HttpOnly 쿠키로 발급되고
    데이터베이스에는 SHA-256 해시만 저장됩니다.
servers:
  - url: https://api.example.com
    description: Production
  - url: http://localhost:8080
    description: Local dev
tags:
  - name: Auth
    description: 인증/세션
paths:
  /auth/login:
    post:
      tags: [Auth]
      summary: 로그인 (세션 발급)
      description: 이메일과 비밀번호를 검증하고 HttpOnly 세션 쿠키를 발급합니다.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
            examples:
              default:
                value:
                  email: admin1@example.com
                  password: SuperStrong!2025
      responses:
        '200':
          description: 로그인 성공. 세션 쿠키가 Set-Cookie 헤더로 내려옵니다.
          headers:
            Set-Cookie:
              description: HttpOnly, Secure, SameSite=Lax 속성의 session 쿠키
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminView'
        '401':
          description: 인증 실패
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: 레이트 리밋 초과
          headers:
            X-RateLimit-Limit:
              schema: { type: integer }
            X-RateLimit-Remaining:
              schema: { type: integer }
            Retry-After:
              schema: { type: integer, description: '초 단위' }
  /auth/logout:
    post:
      tags: [Auth]
      summary: 로그아웃 (세션 종료)
      description: 현재 세션을 무효화하고 쿠키를 즉시 만료시킵니다.
      security:
        - cookieAuth: []
      responses:
        '204':
          description: 성공 (본문 없음). Set-Cookie로 session 쿠키 만료.
        '401':
          description: 세션 없음/만료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /me:
    get:
      tags: [Auth]
      summary: 내 프로필 조회
      description: 유효한 세션 쿠키가 필요합니다.
      security:
        - cookieAuth: []
      responses:
        '200':
          description: 현재 로그인한 관리자 정보
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AdminView'
        '401':
          description: 세션 없음/만료
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session
      description: HttpOnly Secure 쿠키. SameSite=Lax 권장.
  schemas:
    LoginRequest:
      type: object
      required: [email, password]
      properties:
        email:
          type: string
          format: email
          example: admin1@example.com
        password:
          type: string
          format: password
          minLength: 8
          example: SuperStrong!2025
    AdminView:
      type: object
      properties:
        id:
          type: string
          example: 66c5f2f3a6f3b97c1a2b1f90
        email:
          type: string
          format: email
          example: admin1@example.com
        role:
          type: string
          example: ADMIN
        permissions:
          type: array
          items: { type: string }
          example: [RECRUIT_READ, COMPLAINT_READ]
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: AUTH_INVALID_CREDENTIALS
        message:
          type: string
          example: 이메일 또는 비밀번호가 올바르지 않습니다.
externalDocs:
  description: 운영 수칙
  url: https://example.com/docs/security
